'use strict';

exports.Genders = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
};

exports.ClanRanks = {
  MEMBER: 'MEMBER',
  COLEADER: 'COLEADER',
  LEADER: 'LEADER',
};

exports.LootboxTypes = {
  DEFAULT: 'DEFAULT',
  EASTER: 'EASTER',
  HALLOWEEN: 'HALLOWEEN',
  CHRISTMAS: 'CHRISTMAS',
  ROLE_CARDS: 'ROLE_CARDS',
  LEVEL_UP_CARD: 'LEVEL_UP_CARD',
};

exports.RewardTypes = {
  GOLD: 'GOLD',
  ROSE_PACKAGE: 'ROSE_PACKAGE',
  GEM: 'GEM',
  XP: 'XP',
  ROLE_CARD: 'ROLE_CARD',
  AVATAR_ITEM: 'AVATAR_ITEM',
  LOOT_BOX: 'LOOT_BOX',
  PROFILE_ICON: 'PROFILE_ICON',
  EMOJI: 'EMOJI',
  LOADING_SCREEN: 'LOADING_SCREEN',
  ROLE_CARD_ABILITY_EXCHANGE_VOUCHER: 'ROLE_CARD_ABILITY_EXCHANGE_VOUCHER',
  TALISMAN: 'TALISMAN',
};

exports.RankedTiers = {
  NONE: 'NONE',
  COPPER: 'COPPER',
  BRONZE: 'BRONZE',
  SILVER: 'SILVER',
  GOLD: 'GOLD',
  PLATINUM: 'PLATINUM',
};

exports.Status = {
  DEFAULT: 'DEFAULT',
  PLAY: 'PLAY',
  DND: 'DND',
  OFFLINE: 'OFFLINE',
};

exports.ItemTypes = {
  HAT: 'HAT',
  HAIR: 'HAIR',
  EYES: 'EYES',
  GLASSES: 'GLASSES',
  MOUTH: 'MOUTH',
  MASK: 'MASK',
  CLOTHES: 'CLOTHES',
  FOREGROUND: 'FOREGROUND',
  BACKGROUND: 'BACKGROUND',
  BADGE: 'BADGE',
  GRAVESTONE: 'GRAVESTONE',
};

exports.Rarities = {
  COMMON: 'COMMON',
  RARE: 'RARE',
  EPIC: 'EPIC',
  LEGENDARY: 'LEGENDARY',
};

exports.QuestTypes = {
  GOLD: 0,
  GEM: 1,
};
